version: '3.9'

services:
  db:
    container_name: quotes-db
    build: ./db  # Use the Dockerfile in the 'db' directory to build the image
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quotesdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql  # Persist database data across restarts
    ports:
      - "3306:3306"  # Expose MySQL port to host for testing or connecting externally

  api:
    container_name: quotes-api
    build: ./api  # Use the Dockerfile in the 'api' directory to build the image
    depends_on:
      - db  # Ensure db is up before starting the API
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: quotesdb
    ports:
      - "5001:5001"  # Expose API on port 5001 for development

  app:
    container_name: quotes-frontend
    build: ./app  # Use the Dockerfile in the 'app' directory to build the image
    depends_on:
      - api  # Ensure API is up before starting the frontend
    ports:
      - "5002:5002"  # Expose frontend on port 5002

volumes:
  db-data:  # Volume to persist MySQL data
