apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-deployment-knative
  namespace: k8s-ns
spec:
  template:
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - image: gitlabregistry.exxeta.com/gedeom.tsasse/serverlessk8s/app
          ports:
            - containerPort: 5002
          env:
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config-knative
                  key: API_HOST





    #  traffic:
    #   - latestRevision: true
    #    percent: 50
    # - latestRevision: false
    #  percent: 50
  # revisionName: todo-app-00001
