apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-pod-policy
  namespace: k8s-ns
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api
              env: dev
      ports:
        - protocol: TCP
          port: 3306