apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: k8s-ns
spec:
  selector:
    matchLabels:
      app: app
      env: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: app
        env: dev
    spec:
      containers:
        - name: app-container
          image: gitlabregistry.exxeta.com/gedeom.tsasse/serverlessk8s/app
          ports:
            - containerPort: 5002
          env: 
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: API_HOST
      imagePullSecrets:
      - name: gitlab-registry

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: k8s-ns
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002