apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: k8s-ns
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: "2000Mi"
    limits.cpu: "3"
    limits.memory: "4Gi"
    pods: "10"