apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec: 
      containers:
      - name: {{ .Values.app.name }}
        image:  {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
spec:
  type: {{ .Values.app.serviceType }}
  selector:
    app: {{ .Values.app.name }}
  ports:
  - port: {{ .Values.app.port }}
    targetPort: {{ .Values.app.port }}